name: Update GitHub Stats

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate GitHub Stats
        uses: cicirello/user-statistician@v1
        with:
          image-file: images/github-stats.svg
          colors: dark-dimmed
          include-title: false
          hide-keys: joined,mostStarred,mostForked,followers,following,private
          max-languages: 6
          commit-and-push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
